
/*****
*
* Copyright (C) 2004-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@prelude-ids.com>
* Author: Nicolas Delon <nicolas.delon@prelude-ids.com>
*
* This file is part of the Libidmefv2 library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/*
 * This file was automatically generated by our generator, version 1
 *
 * Do not make changes to this file unless you know what you are doing.
 * modify the template interface file instead.
 * IDMEFV2 version : Not released yet
 * Template file: generate-top-level-class-print.c.mako
 *
 */

#include "config.h"
#include "libmissing.h"

#include <stdio.h>

#include "idmefv2.h"
#include "idmefv2-tree-wrap.h"
#include "idmefv2-message-print.h"


static int indent = 0;

static void print_indent(libidmefv2_io_t *fd)
{
        int cnt;

        for ( cnt = 0; cnt < indent; cnt++ )
                libidmefv2_io_write(fd, " ", 1);
}



static void print_string(libidmefv2_string_t *string, libidmefv2_io_t *fd)
{
        if ( libidmefv2_string_is_empty(string) )
                libidmefv2_io_write(fd, "<empty>", 7);
        else
                libidmefv2_io_write(fd, libidmefv2_string_get_string(string), libidmefv2_string_get_len(string));
}



static void print_uint8(uint8_t i, libidmefv2_io_t *fd)
{
        int len;
        char buf[sizeof("255")];

        /*
         * %hh convertion specifier is not portable.
         */
        len = snprintf(buf, sizeof(buf), "%u", (unsigned int) i);
        libidmefv2_io_write(fd, buf, len);
}


static void print_uint16(uint16_t i, libidmefv2_io_t *fd)
{
        int len;
        char buf[sizeof("65535")];

        len = snprintf(buf, sizeof(buf), "%hu", i);
        libidmefv2_io_write(fd, buf, len);
}


static void print_int32(int32_t i, libidmefv2_io_t *fd)
{
        int len;
        char buf[sizeof("4294967296")];

        len = snprintf(buf, sizeof(buf), "%d", i);
        libidmefv2_io_write(fd, buf, len);
}


static void print_uint32(uint32_t i, libidmefv2_io_t *fd)
{
        int len;
        char buf[sizeof("4294967296")];

        len = snprintf(buf, sizeof(buf), "%u", i);
        libidmefv2_io_write(fd, buf, len);
}



static void print_uint64(uint64_t i, libidmefv2_io_t *fd)
{
        int len;
        char buf[sizeof("18446744073709551616")];

        len = snprintf(buf, sizeof(buf), "%" LIBIDMEFV2_PRIu64, i);
        libidmefv2_io_write(fd, buf, len);
}



static void print_float(float f, libidmefv2_io_t *fd)
{
        int len;
        char buf[32];

        len = snprintf(buf, sizeof(buf), "%f", f);
        libidmefv2_io_write(fd, buf, len);
}




static void print_time(idmefv2_time_t *t, libidmefv2_io_t *fd)
{
        int len;
        time_t _time;
        struct tm _tm;
        char tmp[32], buf[128];

        _time = idmefv2_time_get_sec(t) + idmefv2_time_get_gmt_offset(t);

        if ( ! gmtime_r(&_time, &_tm) )
                return;

        len = strftime(tmp, sizeof(tmp), "%d/%m/%Y %H:%M:%S", &_tm);
        if ( len == 0 )
                return;

        len = snprintf(buf, sizeof(buf), "%s.%u %+.2d:%.2d",
                       tmp, idmefv2_time_get_usec(t), idmefv2_time_get_gmt_offset(t) / 3600,
                       idmefv2_time_get_gmt_offset(t) % 3600 / 60);

        libidmefv2_io_write(fd, buf, len);
}



/* print data as a string */

static int print_data(idmefv2_data_t *data, libidmefv2_io_t *fd)
{
        int ret;
        libidmefv2_string_t *out;

        ret = libidmefv2_string_new(&out);
        if ( ret < 0 )
                return ret;

        ret = idmefv2_data_to_string(data, out);
        if ( ret < 0 ) {
                libidmefv2_string_destroy(out);
                return ret;
        }

        libidmefv2_io_write(fd, libidmefv2_string_get_string(out), libidmefv2_string_get_len(out));
        libidmefv2_string_destroy(out);

        return 0;
}



static void print_enum(const char *s, int i, libidmefv2_io_t *fd)
{
        int len;
        char buf[512];

        if ( ! s )
                s = "<invalid enum value>";

        len = snprintf(buf, sizeof(buf), "%s (%d)", s, i);
        libidmefv2_io_write(fd, buf, len);
}
/**
 * idmefv2_address_print:
 * @ptr: Pointer to an idmefv2_address_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_address_print(idmefv2_address_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_address_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_address_get_translation(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "translation: ", sizeof("translation: ") - 1);
                        print_enum(idmefv2_address_translation_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

    {
                int i = idmefv2_address_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_address_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "vlan_name: ";
                field = idmefv2_address_get_vlan_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "vlan_num: ";
                field = idmefv2_address_get_vlan_num(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "address: ";
                field = idmefv2_address_get_address(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "netmask: ";
                field = idmefv2_address_get_netmask(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_user_id_print:
 * @ptr: Pointer to an idmefv2_user_id_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_user_id_print(idmefv2_user_id_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_user_id_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_user_id_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_user_id_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "tty: ";
                field = idmefv2_user_id_get_tty(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_user_id_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "number: ";
                field = idmefv2_user_id_get_number(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_node_name_print:
 * @ptr: Pointer to an idmefv2_node_name_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_node_name_print(idmefv2_node_name_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_node_name_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_node_name_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_node_name_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_location_print:
 * @ptr: Pointer to an idmefv2_location_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_location_print(idmefv2_location_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_location_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                float *field;
                const char tmp[] = "latitude: ";
                field = idmefv2_location_get_latitude(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_float(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                float *field;
                const char tmp[] = "longitude: ";
                field = idmefv2_location_get_longitude(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_float(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                float *field;
                const char tmp[] = "altitude: ";
                field = idmefv2_location_get_altitude(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_float(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "country: ";
                field = idmefv2_location_get_country(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "city: ";
                field = idmefv2_location_get_city(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "postcode: ";
                field = idmefv2_location_get_postcode(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_interface_print:
 * @ptr: Pointer to an idmefv2_interface_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_interface_print(idmefv2_interface_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_interface_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_interface_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_interface_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "meaning: ";
                field = idmefv2_interface_get_meaning(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                idmefv2_address_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_interface_get_next_address(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "address(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_address_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_file_access_print:
 * @ptr: Pointer to an idmefv2_file_access_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_file_access_print(idmefv2_file_access_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                idmefv2_user_id_t *field;

                field = idmefv2_file_access_get_user_id(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "user_id:\n", sizeof("user_id:\n") - 1);
                        idmefv2_user_id_print(field, fd);
                }
        }

    {
                int i = idmefv2_file_access_get_permission(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "permission: ", sizeof("permission: ") - 1);
                        print_enum(idmefv2_file_access_permission_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_inode_print:
 * @ptr: Pointer to an idmefv2_inode_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_inode_print(idmefv2_inode_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                uint32_t *field;
                const char tmp[] = "number: ";
                field = idmefv2_inode_get_number(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "major_device: ";
                field = idmefv2_inode_get_major_device(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "minor_device: ";
                field = idmefv2_inode_get_minor_device(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "c_major_device: ";
                field = idmefv2_inode_get_c_major_device(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "c_minor_device: ";
                field = idmefv2_inode_get_c_minor_device(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_time_t *field;
                const char tmp[] = "change_time: ";
                field = idmefv2_inode_get_change_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_checksum_print:
 * @ptr: Pointer to an idmefv2_checksum_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_checksum_print(idmefv2_checksum_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "value: ";
                field = idmefv2_checksum_get_value(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "key: ";
                field = idmefv2_checksum_get_key(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_checksum_get_algorithm(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "algorithm: ", sizeof("algorithm: ") - 1);
                        print_enum(idmefv2_checksum_algorithm_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_stream_print:
 * @ptr: Pointer to an idmefv2_stream_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_stream_print(idmefv2_stream_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_stream_get_offsetunit(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "offsetunit: ", sizeof("offsetunit: ") - 1);
                        print_enum(idmefv2_stream_offsetunit_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                uint32_t *field;
                const char tmp[] = "offset: ";
                field = idmefv2_stream_get_offset(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_file_print:
 * @ptr: Pointer to an idmefv2_file_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_file_print(idmefv2_file_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_file_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_file_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "path: ";
                field = idmefv2_file_get_path(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_time_t *field;
                const char tmp[] = "create_time: ";
                field = idmefv2_file_get_create_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_time_t *field;
                const char tmp[] = "modify_time: ";
                field = idmefv2_file_get_modify_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_time_t *field;
                const char tmp[] = "access_time: ";
                field = idmefv2_file_get_access_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint64_t *field;
                const char tmp[] = "data_size: ";
                field = idmefv2_file_get_data_size(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint64(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint64_t *field;
                const char tmp[] = "disk_size: ";
                field = idmefv2_file_get_disk_size(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint64(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                idmefv2_file_access_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_file_get_next_file_access(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "file_access(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_file_access_print(elem, fd);



                        cnt++;
                }
        }
        {
                char buf[128];
                idmefv2_linkage_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_file_get_next_linkage(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "linkage(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_linkage_print(elem, fd);



                        cnt++;
                }
        }

        {
                idmefv2_inode_t *field;

                field = idmefv2_file_get_inode(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "inode:\n", sizeof("inode:\n") - 1);
                        idmefv2_inode_print(field, fd);
                }
        }
        {
                char buf[128];
                idmefv2_checksum_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_file_get_next_checksum(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "checksum(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_checksum_print(elem, fd);



                        cnt++;
                }
        }

    {
                int i = idmefv2_file_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_file_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "file_type: ";
                field = idmefv2_file_get_file_type(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_container_t *field;

                field = idmefv2_file_get_container(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "container:\n", sizeof("container:\n") - 1);
                        idmefv2_container_print(field, fd);
                }
        }

        {
                idmefv2_stream_t *field;

                field = idmefv2_file_get_stream(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "stream:\n", sizeof("stream:\n") - 1);
                        idmefv2_stream_print(field, fd);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_linkage_print:
 * @ptr: Pointer to an idmefv2_linkage_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_linkage_print(idmefv2_linkage_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_linkage_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_linkage_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_linkage_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "path: ";
                field = idmefv2_linkage_get_path(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_file_t *field;

                field = idmefv2_linkage_get_file(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "file:\n", sizeof("file:\n") - 1);
                        idmefv2_file_print(field, fd);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_container_print:
 * @ptr: Pointer to an idmefv2_container_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_container_print(idmefv2_container_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_container_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "path: ";
                field = idmefv2_container_get_path(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_file_t *field;

                field = idmefv2_container_get_file(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "file:\n", sizeof("file:\n") - 1);
                        idmefv2_file_print(field, fd);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_process_print:
 * @ptr: Pointer to an idmefv2_process_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_process_print(idmefv2_process_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_process_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_process_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "pid: ";
                field = idmefv2_process_get_pid(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "path: ";
                field = idmefv2_process_get_path(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                libidmefv2_string_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_process_get_next_arg(ptr, elem)) ) {
                        print_indent(fd);
                        len = snprintf(buf, sizeof(buf), "arg(%d): ", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        print_string(elem, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);




                        cnt++;
                }
        }
        {
                char buf[128];
                libidmefv2_string_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_process_get_next_env(ptr, elem)) ) {
                        print_indent(fd);
                        len = snprintf(buf, sizeof(buf), "env(%d): ", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        print_string(elem, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);




                        cnt++;
                }
        }

        {
                uint32_t *field;
                const char tmp[] = "tid: ";
                field = idmefv2_process_get_tid(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_service_print:
 * @ptr: Pointer to an idmefv2_service_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_service_print(idmefv2_service_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_service_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "iana_protocol_number: ";
                field = idmefv2_service_get_iana_protocol_number(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "iana_protocol_name: ";
                field = idmefv2_service_get_iana_protocol_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_service_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "port: ";
                field = idmefv2_service_get_port(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "portlist: ";
                field = idmefv2_service_get_portlist(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "protocol: ";
                field = idmefv2_service_get_protocol(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_node_print:
 * @ptr: Pointer to an idmefv2_node_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_node_print(idmefv2_node_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_node_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_location_t *field;

                field = idmefv2_node_get_location(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "location:\n", sizeof("location:\n") - 1);
                        idmefv2_location_print(field, fd);
                }
        }
        {
                char buf[128];
                idmefv2_node_name_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_node_get_next_node_name(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "node_name(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_node_name_print(elem, fd);



                        cnt++;
                }
        }
        {
                char buf[128];
                idmefv2_interface_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_node_get_next_interface(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "interface(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_interface_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_user_print:
 * @ptr: Pointer to an idmefv2_user_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_user_print(idmefv2_user_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_user_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_user_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_user_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }
        {
                char buf[128];
                idmefv2_user_id_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_user_get_next_user_id(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "user_id(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_user_id_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_impact_type_print:
 * @ptr: Pointer to an idmefv2_impact_type_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_impact_type_print(idmefv2_impact_type_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_impact_type_get_origin(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "origin: ", sizeof("origin: ") - 1);
                        print_enum(idmefv2_impact_type_origin_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "meaning: ";
                field = idmefv2_impact_type_get_meaning(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_impact_type_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "url: ";
                field = idmefv2_impact_type_get_url(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_source_print:
 * @ptr: Pointer to an idmefv2_source_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_source_print(idmefv2_source_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_source_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_source_get_spoofed(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "spoofed: ", sizeof("spoofed: ") - 1);
                        print_enum(idmefv2_source_spoofed_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                idmefv2_node_t *field;

                field = idmefv2_source_get_node(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "node:\n", sizeof("node:\n") - 1);
                        idmefv2_node_print(field, fd);
                }
        }

        {
                idmefv2_user_t *field;

                field = idmefv2_source_get_user(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "user:\n", sizeof("user:\n") - 1);
                        idmefv2_user_print(field, fd);
                }
        }

        {
                idmefv2_process_t *field;

                field = idmefv2_source_get_process(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "process:\n", sizeof("process:\n") - 1);
                        idmefv2_process_print(field, fd);
                }
        }

        {
                idmefv2_service_t *field;

                field = idmefv2_source_get_service(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "service:\n", sizeof("service:\n") - 1);
                        idmefv2_service_print(field, fd);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_target_print:
 * @ptr: Pointer to an idmefv2_target_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_target_print(idmefv2_target_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_target_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_target_get_decoy(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "decoy: ", sizeof("decoy: ") - 1);
                        print_enum(idmefv2_target_decoy_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                idmefv2_node_t *field;

                field = idmefv2_target_get_node(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "node:\n", sizeof("node:\n") - 1);
                        idmefv2_node_print(field, fd);
                }
        }

        {
                idmefv2_user_t *field;

                field = idmefv2_target_get_user(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "user:\n", sizeof("user:\n") - 1);
                        idmefv2_user_print(field, fd);
                }
        }

        {
                idmefv2_process_t *field;

                field = idmefv2_target_get_process(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "process:\n", sizeof("process:\n") - 1);
                        idmefv2_process_print(field, fd);
                }
        }

        {
                idmefv2_service_t *field;

                field = idmefv2_target_get_service(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "service:\n", sizeof("service:\n") - 1);
                        idmefv2_service_print(field, fd);
                }
        }

        {
                idmefv2_file_t *field;

                field = idmefv2_target_get_file(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "file:\n", sizeof("file:\n") - 1);
                        idmefv2_file_print(field, fd);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_original_data_print:
 * @ptr: Pointer to an idmefv2_original_data_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_original_data_print(idmefv2_original_data_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                idmefv2_time_t *field;
                const char tmp[] = "timestamp: ";
                field = idmefv2_original_data_get_timestamp(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_original_data_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_data_t *field;
                const char tmp[] = "data: ";
                field = idmefv2_original_data_get_data(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_data(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_node_t *field;

                field = idmefv2_original_data_get_node(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "node:\n", sizeof("node:\n") - 1);
                        idmefv2_node_print(field, fd);
                }
        }

        {
                idmefv2_file_t *field;

                field = idmefv2_original_data_get_file(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "file:\n", sizeof("file:\n") - 1);
                        idmefv2_file_print(field, fd);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_observable_print:
 * @ptr: Pointer to an idmefv2_observable_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_observable_print(idmefv2_observable_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_observable_get_origin(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "origin: ", sizeof("origin: ") - 1);
                        print_enum(idmefv2_observable_origin_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "meaning: ";
                field = idmefv2_observable_get_meaning(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "url: ";
                field = idmefv2_observable_get_url(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_observable_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_taken_action_print:
 * @ptr: Pointer to an idmefv2_taken_action_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_taken_action_print(idmefv2_taken_action_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_taken_action_get_category(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "category: ", sizeof("category: ") - 1);
                        print_enum(idmefv2_taken_action_category_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_reference_print:
 * @ptr: Pointer to an idmefv2_reference_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_reference_print(idmefv2_reference_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_reference_get_origin(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "origin: ", sizeof("origin: ") - 1);
                        print_enum(idmefv2_reference_origin_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "meaning: ";
                field = idmefv2_reference_get_meaning(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "author: ";
                field = idmefv2_reference_get_author(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_time_t *field;
                const char tmp[] = "publication_time: ";
                field = idmefv2_reference_get_publication_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "version: ";
                field = idmefv2_reference_get_version(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_reference_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "url: ";
                field = idmefv2_reference_get_url(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_analyzer_print:
 * @ptr: Pointer to an idmefv2_analyzer_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_analyzer_print(idmefv2_analyzer_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "analyzerid: ";
                field = idmefv2_analyzer_get_analyzerid(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_analyzer_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "manufacturer: ";
                field = idmefv2_analyzer_get_manufacturer(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "model: ";
                field = idmefv2_analyzer_get_model(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "version: ";
                field = idmefv2_analyzer_get_version(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_analyzer_get_class(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "class: ", sizeof("class: ") - 1);
                        print_enum(idmefv2_analyzer_class_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "ostype: ";
                field = idmefv2_analyzer_get_ostype(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "osversion: ";
                field = idmefv2_analyzer_get_osversion(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "ext_class: ";
                field = idmefv2_analyzer_get_ext_class(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_analyzer_get_analyzeraction(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "analyzeraction: ", sizeof("analyzeraction: ") - 1);
                        print_enum(idmefv2_analyzer_analyzeraction_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "actionhistory: ";
                field = idmefv2_analyzer_get_actionhistory(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_node_t *field;

                field = idmefv2_analyzer_get_node(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "node:\n", sizeof("node:\n") - 1);
                        idmefv2_node_print(field, fd);
                }
        }

        {
                idmefv2_process_t *field;

                field = idmefv2_analyzer_get_process(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "process:\n", sizeof("process:\n") - 1);
                        idmefv2_process_print(field, fd);
                }
        }

        {
                idmefv2_time_t *field;
                const char tmp[] = "analyzer_time: ";
                field = idmefv2_analyzer_get_analyzer_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_additional_data_print:
 * @ptr: Pointer to an idmefv2_additional_data_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_additional_data_print(idmefv2_additional_data_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "meaning: ";
                field = idmefv2_additional_data_get_meaning(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



    {
                int i = idmefv2_additional_data_get_type(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "type: ", sizeof("type: ") - 1);
                        print_enum(idmefv2_additional_data_type_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                idmefv2_data_t *field;
                const char tmp[] = "data: ";
                field = idmefv2_additional_data_get_data(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        if ( idmefv2_additional_data_get_type(ptr) != IDMEFV2_ADDITIONAL_DATA_TYPE_NTPSTAMP )
                                print_data(field, fd);
                        else {
                                int ret;
                                uint64_t i;
                                libidmefv2_string_t *out;

                                ret = libidmefv2_string_new(&out);
                                if ( ret < 0 )
                                        return;

                                i = idmefv2_data_get_int(field);
                                ret = libidmefv2_string_sprintf(out, "0x%" LIBIDMEFV2_PRIx32 ".0x%" LIBIDMEFV2_PRIx32 "", (uint32_t) (i >> 32), (uint32_t) i);
                                if ( ret < 0 ) {
                                        libidmefv2_string_destroy(out);
                                        return;
                                }

                                libidmefv2_io_write(fd, libidmefv2_string_get_string(out), libidmefv2_string_get_len(out));
                                libidmefv2_string_destroy(out);
                        }
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_correlation_alert_print:
 * @ptr: Pointer to an idmefv2_correlation_alert_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_correlation_alert_print(idmefv2_correlation_alert_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "name: ";
                field = idmefv2_correlation_alert_get_name(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                libidmefv2_string_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_correlation_alert_get_next_alertident(ptr, elem)) ) {
                        print_indent(fd);
                        len = snprintf(buf, sizeof(buf), "alertident(%d): ", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        print_string(elem, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);




                        cnt++;
                }
        }

        {
                uint32_t *field;
                const char tmp[] = "duration: ";
                field = idmefv2_correlation_alert_get_duration(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "counter: ";
                field = idmefv2_correlation_alert_get_counter(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_analysis_data_print:
 * @ptr: Pointer to an idmefv2_analysis_data_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_analysis_data_print(idmefv2_analysis_data_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;

        {
                char buf[128];
                idmefv2_observable_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_analysis_data_get_next_observable(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "observable(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_observable_print(elem, fd);



                        cnt++;
                }
        }
        {
                char buf[128];
                idmefv2_original_data_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_analysis_data_get_next_original_data(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "original_data(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_original_data_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_confidence_print:
 * @ptr: Pointer to an idmefv2_confidence_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_confidence_print(idmefv2_confidence_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_confidence_get_rating(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "rating: ", sizeof("rating: ") - 1);
                        print_enum(idmefv2_confidence_rating_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        indent -= 8;
}
/**
 * idmefv2_impact_print:
 * @ptr: Pointer to an idmefv2_impact_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_impact_print(idmefv2_impact_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_impact_get_severity(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "severity: ", sizeof("severity: ") - 1);
                        print_enum(idmefv2_impact_severity_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

    {
                int i = idmefv2_impact_get_completion(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "completion: ", sizeof("completion: ") - 1);
                        print_enum(idmefv2_impact_completion_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

    {
                int i = idmefv2_impact_get_availability(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "availability: ", sizeof("availability: ") - 1);
                        print_enum(idmefv2_impact_availability_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

    {
                int i = idmefv2_impact_get_integrity(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "integrity: ", sizeof("integrity: ") - 1);
                        print_enum(idmefv2_impact_integrity_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

    {
                int i = idmefv2_impact_get_confidentiality(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "confidentiality: ", sizeof("confidentiality: ") - 1);
                        print_enum(idmefv2_impact_confidentiality_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                libidmefv2_string_t *field;
                const char tmp[] = "description: ";
                field = idmefv2_impact_get_description(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                idmefv2_impact_type_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_impact_get_next_impact_type(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "impact_type(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_impact_type_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_recommanded_action_print:
 * @ptr: Pointer to an idmefv2_recommanded_action_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_recommanded_action_print(idmefv2_recommanded_action_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


    {
                int i = idmefv2_recommanded_action_get_action(ptr);



                {
                        print_indent(fd);
                        libidmefv2_io_write(fd, "action: ", sizeof("action: ") - 1);
                        print_enum(idmefv2_recommanded_action_action_to_string(i), i, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }

        {
                uint32_t *field;
                const char tmp[] = "step: ";
                field = idmefv2_recommanded_action_get_step(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        indent -= 8;
}
/**
 * idmefv2_assessment_print:
 * @ptr: Pointer to an idmefv2_assessment_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_assessment_print(idmefv2_assessment_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                idmefv2_impact_t *field;

                field = idmefv2_assessment_get_impact(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "impact:\n", sizeof("impact:\n") - 1);
                        idmefv2_impact_print(field, fd);
                }
        }
        {
                char buf[128];
                idmefv2_taken_action_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_assessment_get_next_taken_action(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "taken_action(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_taken_action_print(elem, fd);



                        cnt++;
                }
        }

        {
                idmefv2_confidence_t *field;

                field = idmefv2_assessment_get_confidence(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "confidence:\n", sizeof("confidence:\n") - 1);
                        idmefv2_confidence_print(field, fd);
                }
        }
        {
                char buf[128];
                idmefv2_recommanded_action_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_assessment_get_next_recommanded_action(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "recommanded_action(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_recommanded_action_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_classification_print:
 * @ptr: Pointer to an idmefv2_classification_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_classification_print(idmefv2_classification_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "ident: ";
                field = idmefv2_classification_get_ident(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "text: ";
                field = idmefv2_classification_get_text(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                idmefv2_reference_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_classification_get_next_reference(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "reference(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_reference_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_heartbeat_print:
 * @ptr: Pointer to an idmefv2_heartbeat_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_heartbeat_print(idmefv2_heartbeat_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "messageid: ";
                field = idmefv2_heartbeat_get_messageid(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_analyzer_t *field;

                field = idmefv2_heartbeat_get_analyzer(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "analyzer:\n", sizeof("analyzer:\n") - 1);
                        idmefv2_analyzer_print(field, fd);
                }
        }

        {
                idmefv2_time_t *field;
                const char tmp[] = "create_time: ";
                field = idmefv2_heartbeat_get_create_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                uint32_t *field;
                const char tmp[] = "heartbeat_interval: ";
                field = idmefv2_heartbeat_get_heartbeat_interval(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_uint32(*field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                idmefv2_additional_data_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_heartbeat_get_next_additional_data(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "additional_data(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_additional_data_print(elem, fd);



                        cnt++;
                }
        }

        indent -= 8;
}
/**
 * idmefv2_alert_print:
 * @ptr: Pointer to an idmefv2_alert_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_alert_print(idmefv2_alert_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;


        indent += 8;


        {
                libidmefv2_string_t *field;
                const char tmp[] = "messageid: ";
                field = idmefv2_alert_get_messageid(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                libidmefv2_string_t *field;
                const char tmp[] = "analyzerhash: ";
                field = idmefv2_alert_get_analyzerhash(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        {
                char buf[128];
                idmefv2_analyzer_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_alert_get_next_analyzer(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "analyzer(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_analyzer_print(elem, fd);



                        cnt++;
                }
        }

        {
                idmefv2_time_t *field;
                const char tmp[] = "create_time: ";
                field = idmefv2_alert_get_create_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_classification_t *field;

                field = idmefv2_alert_get_classification(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "classification:\n", sizeof("classification:\n") - 1);
                        idmefv2_classification_print(field, fd);
                }
        }

        {
                idmefv2_time_t *field;
                const char tmp[] = "detect_time: ";
                field = idmefv2_alert_get_detect_time(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_time(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }



        {
                idmefv2_analysis_data_t *field;

                field = idmefv2_alert_get_analysis_data(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "analysis_data:\n", sizeof("analysis_data:\n") - 1);
                        idmefv2_analysis_data_print(field, fd);
                }
        }
        {
                char buf[128];
                idmefv2_source_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_alert_get_next_source(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "source(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_source_print(elem, fd);



                        cnt++;
                }
        }
        {
                char buf[128];
                idmefv2_target_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_alert_get_next_target(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "target(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_target_print(elem, fd);



                        cnt++;
                }
        }

        {
                idmefv2_assessment_t *field;

                field = idmefv2_alert_get_assessment(ptr);

                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd,  "assessment:\n", sizeof("assessment:\n") - 1);
                        idmefv2_assessment_print(field, fd);
                }
        }
        {
                char buf[128];
                idmefv2_additional_data_t *elem = NULL;
                int cnt = 0, len;

                while ( (elem = idmefv2_alert_get_next_additional_data(ptr, elem)) ) {
                        print_indent(fd);

                        len = snprintf(buf, sizeof(buf), "additional_data(%d): \n", cnt);
                        libidmefv2_io_write(fd, buf, len);
                        idmefv2_additional_data_print(elem, fd);



                        cnt++;
                }
        }
        switch ( idmefv2_alert_get_type(ptr) ) {


        case IDMEFV2_ALERT_TYPE_CORRELATION:
                print_indent(fd);
                libidmefv2_io_write(fd, "correlation_alert:\n", sizeof("correlation_alert:\n") - 1);
                idmefv2_correlation_alert_print(idmefv2_alert_get_correlation_alert(ptr), fd);
                break;

        default:
                break;
        }

        indent -= 8;
}
/**
 * idmefv2_message_print:
 * @ptr: Pointer to an idmefv2_message_t object.
 * @fd: Pointer to a #libidmefv2_io_t object where to print @ptr to.
 *
 * This function will convert @ptr to a string suitable for writing,
 * and write it to the provided @fd descriptor.
 */
void idmefv2_message_print(idmefv2_message_t *ptr, libidmefv2_io_t *fd)
{
        if ( ! ptr )
                return;




        {
                libidmefv2_string_t *field;
                const char tmp[] = "version: ";
                field = idmefv2_message_get_version(ptr);
                if ( field ) {
                        print_indent(fd);
                        libidmefv2_io_write(fd, tmp, sizeof(tmp) - 1);
                        print_string(field, fd);
                        libidmefv2_io_write(fd, "\n", sizeof("\n") - 1);
                }
        }


        switch ( idmefv2_message_get_type(ptr) ) {


        case IDMEFV2_MESSAGE_TYPE_ALERT:
                print_indent(fd);
                libidmefv2_io_write(fd, "alert:\n", sizeof("alert:\n") - 1);
                idmefv2_alert_print(idmefv2_message_get_alert(ptr), fd);
                break;


        case IDMEFV2_MESSAGE_TYPE_HEARTBEAT:
                print_indent(fd);
                libidmefv2_io_write(fd, "heartbeat:\n", sizeof("heartbeat:\n") - 1);
                idmefv2_heartbeat_print(idmefv2_message_get_heartbeat(ptr), fd);
                break;

        default:
                break;
        }

}
