
/*****
*
* Copyright (C) 2003-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@prelude-ids.com>
*
* This file is part of the Libidmefv2 library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/*
 * This file was automatically generated by our generator, version 1
 *
 * Do not make changes to this file unless you know what you are doing.
 * modify the template interface file instead.
 * IDMEFV2 version : Not released yet
 * Template file: generate-additional-data.c.mako
 *
 */

#ifndef _LIBIDMEFV2_IDMEFV2_MESSAGE_PRINT_JSON_H
#define _LIBIDMEFV2_IDMEFV2_MESSAGE_PRINT_JSON_H

#ifdef __cplusplus
 extern "C" {
#endif
int idmefv2_address_print_json(idmefv2_address_t *ptr, libidmefv2_io_t *fd);
int idmefv2_user_id_print_json(idmefv2_user_id_t *ptr, libidmefv2_io_t *fd);
int idmefv2_node_name_print_json(idmefv2_node_name_t *ptr, libidmefv2_io_t *fd);
int idmefv2_location_print_json(idmefv2_location_t *ptr, libidmefv2_io_t *fd);
int idmefv2_interface_print_json(idmefv2_interface_t *ptr, libidmefv2_io_t *fd);
int idmefv2_file_access_print_json(idmefv2_file_access_t *ptr, libidmefv2_io_t *fd);
int idmefv2_inode_print_json(idmefv2_inode_t *ptr, libidmefv2_io_t *fd);
int idmefv2_checksum_print_json(idmefv2_checksum_t *ptr, libidmefv2_io_t *fd);
int idmefv2_stream_print_json(idmefv2_stream_t *ptr, libidmefv2_io_t *fd);
int idmefv2_file_print_json(idmefv2_file_t *ptr, libidmefv2_io_t *fd);
int idmefv2_linkage_print_json(idmefv2_linkage_t *ptr, libidmefv2_io_t *fd);
int idmefv2_container_print_json(idmefv2_container_t *ptr, libidmefv2_io_t *fd);
int idmefv2_process_print_json(idmefv2_process_t *ptr, libidmefv2_io_t *fd);
int idmefv2_service_print_json(idmefv2_service_t *ptr, libidmefv2_io_t *fd);
int idmefv2_node_print_json(idmefv2_node_t *ptr, libidmefv2_io_t *fd);
int idmefv2_user_print_json(idmefv2_user_t *ptr, libidmefv2_io_t *fd);
int idmefv2_impact_type_print_json(idmefv2_impact_type_t *ptr, libidmefv2_io_t *fd);
int idmefv2_source_print_json(idmefv2_source_t *ptr, libidmefv2_io_t *fd);
int idmefv2_target_print_json(idmefv2_target_t *ptr, libidmefv2_io_t *fd);
int idmefv2_original_data_print_json(idmefv2_original_data_t *ptr, libidmefv2_io_t *fd);
int idmefv2_observable_print_json(idmefv2_observable_t *ptr, libidmefv2_io_t *fd);
int idmefv2_taken_action_print_json(idmefv2_taken_action_t *ptr, libidmefv2_io_t *fd);
int idmefv2_reference_print_json(idmefv2_reference_t *ptr, libidmefv2_io_t *fd);
int idmefv2_analyzer_print_json(idmefv2_analyzer_t *ptr, libidmefv2_io_t *fd);
int idmefv2_additional_data_print_json(idmefv2_additional_data_t *ptr, libidmefv2_io_t *fd);
int idmefv2_correlation_alert_print_json(idmefv2_correlation_alert_t *ptr, libidmefv2_io_t *fd);
int idmefv2_analysis_data_print_json(idmefv2_analysis_data_t *ptr, libidmefv2_io_t *fd);
int idmefv2_confidence_print_json(idmefv2_confidence_t *ptr, libidmefv2_io_t *fd);
int idmefv2_impact_print_json(idmefv2_impact_t *ptr, libidmefv2_io_t *fd);
int idmefv2_recommanded_action_print_json(idmefv2_recommanded_action_t *ptr, libidmefv2_io_t *fd);
int idmefv2_assessment_print_json(idmefv2_assessment_t *ptr, libidmefv2_io_t *fd);
int idmefv2_classification_print_json(idmefv2_classification_t *ptr, libidmefv2_io_t *fd);
int idmefv2_heartbeat_print_json(idmefv2_heartbeat_t *ptr, libidmefv2_io_t *fd);
int idmefv2_alert_print_json(idmefv2_alert_t *ptr, libidmefv2_io_t *fd);
int idmefv2_message_print_json(idmefv2_message_t *ptr, libidmefv2_io_t *fd);

int idmefv2_message_print_json(idmefv2_message_t *ptr, libidmefv2_io_t *fd);

#ifdef __cplusplus
 }
#endif

#endif /* _LIBIDMEFV2_IDMEFV2_MESSAGE_JSON_H */
