
/*****
*
* Copyright (C) 2003-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@prelude-ids.com>
*
* This file is part of the LibIdemfv2 library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/*
 * This file was automatically generated by our generator, version 1
 *
 * Do not make changes to this file unless you know what you are doing.
 * modify the template interface file instead.
 * IDMEFV2 version : Not released yet
 * Template file: generate-top-level-class-print.h.mako
 *
 */

#ifndef _LIBIDMEFV2_IDMEFV2_MESSAGE_PRINT_H
#define _LIBIDMEFV2_IDMEFV2_MESSAGE_PRINT_H

#ifdef __cplusplus
 extern "C" {
#endif


void idmefv2_address_print(idmefv2_address_t *ptr, libidmefv2_io_t *fd);
void idmefv2_user_id_print(idmefv2_user_id_t *ptr, libidmefv2_io_t *fd);
void idmefv2_node_name_print(idmefv2_node_name_t *ptr, libidmefv2_io_t *fd);
void idmefv2_location_print(idmefv2_location_t *ptr, libidmefv2_io_t *fd);
void idmefv2_interface_print(idmefv2_interface_t *ptr, libidmefv2_io_t *fd);
void idmefv2_file_access_print(idmefv2_file_access_t *ptr, libidmefv2_io_t *fd);
void idmefv2_inode_print(idmefv2_inode_t *ptr, libidmefv2_io_t *fd);
void idmefv2_checksum_print(idmefv2_checksum_t *ptr, libidmefv2_io_t *fd);
void idmefv2_stream_print(idmefv2_stream_t *ptr, libidmefv2_io_t *fd);
void idmefv2_file_print(idmefv2_file_t *ptr, libidmefv2_io_t *fd);
void idmefv2_linkage_print(idmefv2_linkage_t *ptr, libidmefv2_io_t *fd);
void idmefv2_container_print(idmefv2_container_t *ptr, libidmefv2_io_t *fd);
void idmefv2_process_print(idmefv2_process_t *ptr, libidmefv2_io_t *fd);
void idmefv2_service_print(idmefv2_service_t *ptr, libidmefv2_io_t *fd);
void idmefv2_node_print(idmefv2_node_t *ptr, libidmefv2_io_t *fd);
void idmefv2_user_print(idmefv2_user_t *ptr, libidmefv2_io_t *fd);
void idmefv2_impact_type_print(idmefv2_impact_type_t *ptr, libidmefv2_io_t *fd);
void idmefv2_source_print(idmefv2_source_t *ptr, libidmefv2_io_t *fd);
void idmefv2_target_print(idmefv2_target_t *ptr, libidmefv2_io_t *fd);
void idmefv2_original_data_print(idmefv2_original_data_t *ptr, libidmefv2_io_t *fd);
void idmefv2_observable_print(idmefv2_observable_t *ptr, libidmefv2_io_t *fd);
void idmefv2_taken_action_print(idmefv2_taken_action_t *ptr, libidmefv2_io_t *fd);
void idmefv2_reference_print(idmefv2_reference_t *ptr, libidmefv2_io_t *fd);
void idmefv2_analyzer_print(idmefv2_analyzer_t *ptr, libidmefv2_io_t *fd);
void idmefv2_additional_data_print(idmefv2_additional_data_t *ptr, libidmefv2_io_t *fd);
void idmefv2_correlation_alert_print(idmefv2_correlation_alert_t *ptr, libidmefv2_io_t *fd);
void idmefv2_analysis_data_print(idmefv2_analysis_data_t *ptr, libidmefv2_io_t *fd);
void idmefv2_confidence_print(idmefv2_confidence_t *ptr, libidmefv2_io_t *fd);
void idmefv2_impact_print(idmefv2_impact_t *ptr, libidmefv2_io_t *fd);
void idmefv2_recommanded_action_print(idmefv2_recommanded_action_t *ptr, libidmefv2_io_t *fd);
void idmefv2_assessment_print(idmefv2_assessment_t *ptr, libidmefv2_io_t *fd);
void idmefv2_classification_print(idmefv2_classification_t *ptr, libidmefv2_io_t *fd);
void idmefv2_heartbeat_print(idmefv2_heartbeat_t *ptr, libidmefv2_io_t *fd);
void idmefv2_alert_print(idmefv2_alert_t *ptr, libidmefv2_io_t *fd);
void idmefv2_message_print(idmefv2_message_t *ptr, libidmefv2_io_t *fd);

#ifdef __cplusplus
 }
#endif

#endif /* _LIBIDMEFV2_IDMEFV2_MESSAGE_PRINT_H */
