
/*****
*
* Copyright (C) 2001-2016 CS-SI. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoann.v@prelude-ids.com>
* Author: Nicolas Delon <nicolas.delon@prelude-ids.com>
*
* This file is part of the LibIodef library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*
*****/

/*
 * This file was automatically generated by our generator, version 1
 *
 * Do not make changes to this file unless you know what you are doing.
 * modify the template interface file instead.
 * IDMEFV2 version : Not released yet
 * Template file: generate-tree-data.h.mako
 *
 */


typedef struct {
        const char *name;
        libidmefv2_bool_t list;
        libidmefv2_bool_t keyed_list;
        idmefv2_value_type_id_t type;
        idmefv2_class_id_t class;
        int union_id;
} children_list_t;

const children_list_t idmefv2_address_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "translation", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_ADDRESS_TRANSLATION, 0 },


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_ADDRESS_CATEGORY, 0 },


        { "vlan_name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "vlan_num", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "address", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "netmask", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_user_id_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_USER_ID_CATEGORY, 0 },


        { "tty", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "number", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },

};


const children_list_t idmefv2_node_name_children_list[] = {


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_NODE_NAME_CATEGORY, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_location_children_list[] = {


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "latitude", 0, 0, IDMEFV2_VALUE_TYPE_FLOAT, 0, 0 },


        { "longitude", 0, 0, IDMEFV2_VALUE_TYPE_FLOAT, 0, 0 },


        { "altitude", 0, 0, IDMEFV2_VALUE_TYPE_FLOAT, 0, 0 },


        { "country", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "city", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "postcode", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_interface_children_list[] = {


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_INTERFACE_CATEGORY, 0 },


        { "meaning", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "address", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ADDRESS, 0 },

};


const children_list_t idmefv2_file_access_children_list[] = {


        { "user_id", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_USER_ID, 0 },


        { "permission", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_FILE_ACCESS_PERMISSION, 0 },

};


const children_list_t idmefv2_inode_children_list[] = {


        { "number", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "major_device", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "minor_device", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "c_major_device", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "c_minor_device", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "change_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },

};


const children_list_t idmefv2_checksum_children_list[] = {


        { "value", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "key", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "algorithm", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_CHECKSUM_ALGORITHM, 0 },

};


const children_list_t idmefv2_stream_children_list[] = {


        { "offsetunit", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_STREAM_OFFSETUNIT, 0 },


        { "offset", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },

};


const children_list_t idmefv2_file_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "path", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "create_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "modify_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "access_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "data_size", 0, 0, IDMEFV2_VALUE_TYPE_UINT64, 0, 0 },


        { "disk_size", 0, 0, IDMEFV2_VALUE_TYPE_UINT64, 0, 0 },


        { "file_access", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_FILE_ACCESS, 0 },


        { "linkage", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_LINKAGE, 0 },


        { "inode", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_INODE, 0 },


        { "checksum", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_CHECKSUM, 0 },


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_FILE_CATEGORY, 0 },


        { "file_type", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "container", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_CONTAINER, 0 },


        { "stream", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_STREAM, 0 },

};


const children_list_t idmefv2_linkage_children_list[] = {


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_LINKAGE_CATEGORY, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "path", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "file", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_FILE, 0 },

};


const children_list_t idmefv2_container_children_list[] = {


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "path", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "file", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_FILE, 0 },

};


const children_list_t idmefv2_process_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "pid", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "path", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "arg", 1, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "env", 1, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "tid", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },

};


const children_list_t idmefv2_service_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "iana_protocol_number", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "iana_protocol_name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "port", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "portlist", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "protocol", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_node_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "location", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_LOCATION, 0 },


        { "node_name", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_NODE_NAME, 0 },


        { "interface", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_INTERFACE, 0 },

};


const children_list_t idmefv2_user_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_USER_CATEGORY, 0 },


        { "user_id", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_USER_ID, 0 },

};


const children_list_t idmefv2_impact_type_children_list[] = {


        { "origin", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_IMPACT_TYPE_ORIGIN, 0 },


        { "meaning", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_source_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "spoofed", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_SOURCE_SPOOFED, 0 },


        { "node", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_NODE, 0 },


        { "user", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_USER, 0 },


        { "process", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_PROCESS, 0 },


        { "service", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_SERVICE, 0 },

};


const children_list_t idmefv2_target_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "decoy", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_TARGET_DECOY, 0 },


        { "node", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_NODE, 0 },


        { "user", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_USER, 0 },


        { "process", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_PROCESS, 0 },


        { "service", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_SERVICE, 0 },


        { "file", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_FILE, 0 },

};


const children_list_t idmefv2_original_data_children_list[] = {


        { "timestamp", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "data", 0, 0, IDMEFV2_VALUE_TYPE_DATA, 0, 0 },


        { "node", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_NODE, 0 },


        { "file", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_FILE, 0 },

};


const children_list_t idmefv2_observable_children_list[] = {


        { "origin", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_OBSERVABLE_ORIGIN, 0 },


        { "meaning", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_taken_action_children_list[] = {


        { "category", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_TAKEN_ACTION_CATEGORY, 0 },

};


const children_list_t idmefv2_reference_children_list[] = {


        { "origin", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_REFERENCE_ORIGIN, 0 },


        { "meaning", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "author", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "publication_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "version", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "url", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

};


const children_list_t idmefv2_analyzer_children_list[] = {


        { "analyzerid", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "manufacturer", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "model", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "version", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "class", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_ANALYZER_CLASS, 0 },


        { "ostype", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "osversion", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "ext_class", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "analyzeraction", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_ANALYZER_ANALYZERACTION, 0 },


        { "actionhistory", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "node", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_NODE, 0 },


        { "process", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_PROCESS, 0 },


        { "analyzer_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },

};


const children_list_t idmefv2_additional_data_children_list[] = {


        { "meaning", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "type", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_ADDITIONAL_DATA_TYPE, 0 },


        { "data", 0, 0, IDMEFV2_VALUE_TYPE_DATA, 0, 0 },

};


const children_list_t idmefv2_correlation_alert_children_list[] = {


        { "name", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "alertident", 1, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "duration", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "counter", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },

};


const children_list_t idmefv2_analysis_data_children_list[] = {


        { "observable", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_OBSERVABLE, 0 },


        { "original_data", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ORIGINAL_DATA, 0 },

};


const children_list_t idmefv2_confidence_children_list[] = {


        { "rating", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_CONFIDENCE_RATING, 0 },

};


const children_list_t idmefv2_impact_children_list[] = {


        { "severity", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_IMPACT_SEVERITY, 0 },


        { "completion", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_IMPACT_COMPLETION, 0 },


        { "availability", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_IMPACT_AVAILABILITY, 0 },


        { "integrity", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_IMPACT_INTEGRITY, 0 },


        { "confidentiality", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_IMPACT_CONFIDENTIALITY, 0 },


        { "description", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "impact_type", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_IMPACT_TYPE, 0 },

};


const children_list_t idmefv2_recommanded_action_children_list[] = {


        { "action", 0, 0, IDMEFV2_VALUE_TYPE_ENUM, IDMEFV2_CLASS_ID_RECOMMANDED_ACTION_ACTION, 0 },


        { "step", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },

};


const children_list_t idmefv2_assessment_children_list[] = {


        { "impact", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_IMPACT, 0 },


        { "taken_action", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_TAKEN_ACTION, 0 },


        { "confidence", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_CONFIDENCE, 0 },


        { "recommanded_action", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_RECOMMANDED_ACTION, 0 },

};


const children_list_t idmefv2_classification_children_list[] = {


        { "ident", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "text", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "reference", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_REFERENCE, 0 },

};


const children_list_t idmefv2_heartbeat_children_list[] = {


        { "messageid", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "analyzer", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ANALYZER, 0 },


        { "create_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "heartbeat_interval", 0, 0, IDMEFV2_VALUE_TYPE_UINT32, 0, 0 },


        { "additional_data", 1, 1, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },

};


const children_list_t idmefv2_alert_children_list[] = {


        { "messageid", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "analyzerhash", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },


        { "analyzer", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ANALYZER, 0 },


        { "create_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "classification", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_CLASSIFICATION, 0 },


        { "detect_time", 0, 0, IDMEFV2_VALUE_TYPE_TIME, 0, 0 },


        { "analysis_data", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ANALYSIS_DATA, 0 },


        { "source", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_SOURCE, 0 },


        { "target", 1, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_TARGET, 0 },


        { "assessment", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ASSESSMENT, 0 },


        { "additional_data", 1, 1, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ADDITIONAL_DATA, 0 },

        { "correlation_alert", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_CORRELATION_ALERT, /* union ID */ 1 },

};


const children_list_t idmefv2_message_children_list[] = {


        { "version", 0, 0, IDMEFV2_VALUE_TYPE_STRING, 0, 0 },

        { "alert", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_ALERT, /* union ID */ 1 },
        { "heartbeat", 0, 0, IDMEFV2_VALUE_TYPE_CLASS, IDMEFV2_CLASS_ID_HEARTBEAT, /* union ID */ 1 },

};


typedef struct {
        const char *name;
        size_t children_list_elem;
        const children_list_t *children_list;
        int (*get_child)(void *ptr, idmefv2_class_child_id_t child, void **ret);
        int (*new_child)(void *ptr, idmefv2_class_child_id_t child, int n, void **ret);
        int (*destroy_child)(void *ptr, idmefv2_class_child_id_t child, int n);
        int (*to_numeric)(const char *name);
        const char *(*to_string)(int val);
        int (*copy)(const void *src, void *dst);
        int (*clone)(const void *src, void **dst);
        int (*compare)(const void *obj1, const void *obj2);
        int (*print)(const void *obj, libidmefv2_io_t *fd);
        int (*print_json)(const void *obj, libidmefv2_io_t *fd);
        int (*print_binary)(const void *obj, libidmefv2_io_t *fd);
        void *(*ref)(void *src);
        void (*destroy)(void *obj);
        libidmefv2_bool_t is_listed;
} object_data_t;

const object_data_t object_data[] =  {
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 0 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 1 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 2 */
        { "address_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_address_category_to_numeric, (void *) idmefv2_address_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 3  */
        { "address_translation", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_address_translation_to_numeric, (void *) idmefv2_address_translation_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 4  */
        { "address", sizeof(idmefv2_address_children_list) / sizeof(*idmefv2_address_children_list), idmefv2_address_children_list, _idmefv2_address_get_child, _idmefv2_address_new_child, _idmefv2_address_destroy_child, NULL, NULL, (void *) idmefv2_address_copy, (void *) idmefv2_address_clone, (void *) idmefv2_address_compare, (void *) idmefv2_address_print, (void *) idmefv2_address_print_json, (void *) idmefv2_address_write, (void *) idmefv2_address_ref, (void *) idmefv2_address_destroy, 1 }, /* ID: 5 */
        { "user_id_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_user_id_category_to_numeric, (void *) idmefv2_user_id_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 6  */
        { "user_id", sizeof(idmefv2_user_id_children_list) / sizeof(*idmefv2_user_id_children_list), idmefv2_user_id_children_list, _idmefv2_user_id_get_child, _idmefv2_user_id_new_child, _idmefv2_user_id_destroy_child, NULL, NULL, (void *) idmefv2_user_id_copy, (void *) idmefv2_user_id_clone, (void *) idmefv2_user_id_compare, (void *) idmefv2_user_id_print, (void *) idmefv2_user_id_print_json, (void *) idmefv2_user_id_write, (void *) idmefv2_user_id_ref, (void *) idmefv2_user_id_destroy, 1 }, /* ID: 7 */
        { "node_name_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_node_name_category_to_numeric, (void *) idmefv2_node_name_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 8  */
        { "node_name", sizeof(idmefv2_node_name_children_list) / sizeof(*idmefv2_node_name_children_list), idmefv2_node_name_children_list, _idmefv2_node_name_get_child, _idmefv2_node_name_new_child, _idmefv2_node_name_destroy_child, NULL, NULL, (void *) idmefv2_node_name_copy, (void *) idmefv2_node_name_clone, (void *) idmefv2_node_name_compare, (void *) idmefv2_node_name_print, (void *) idmefv2_node_name_print_json, (void *) idmefv2_node_name_write, (void *) idmefv2_node_name_ref, (void *) idmefv2_node_name_destroy, 1 }, /* ID: 9 */
        { "location", sizeof(idmefv2_location_children_list) / sizeof(*idmefv2_location_children_list), idmefv2_location_children_list, _idmefv2_location_get_child, _idmefv2_location_new_child, _idmefv2_location_destroy_child, NULL, NULL, (void *) idmefv2_location_copy, (void *) idmefv2_location_clone, (void *) idmefv2_location_compare, (void *) idmefv2_location_print, (void *) idmefv2_location_print_json, (void *) idmefv2_location_write, (void *) idmefv2_location_ref, (void *) idmefv2_location_destroy, 0 }, /* ID: 10 */
        { "interface_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_interface_category_to_numeric, (void *) idmefv2_interface_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 11  */
        { "interface", sizeof(idmefv2_interface_children_list) / sizeof(*idmefv2_interface_children_list), idmefv2_interface_children_list, _idmefv2_interface_get_child, _idmefv2_interface_new_child, _idmefv2_interface_destroy_child, NULL, NULL, (void *) idmefv2_interface_copy, (void *) idmefv2_interface_clone, (void *) idmefv2_interface_compare, (void *) idmefv2_interface_print, (void *) idmefv2_interface_print_json, (void *) idmefv2_interface_write, (void *) idmefv2_interface_ref, (void *) idmefv2_interface_destroy, 1 }, /* ID: 12 */
        { "file_access_permission", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_file_access_permission_to_numeric, (void *) idmefv2_file_access_permission_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 13  */
        { "file_access", sizeof(idmefv2_file_access_children_list) / sizeof(*idmefv2_file_access_children_list), idmefv2_file_access_children_list, _idmefv2_file_access_get_child, _idmefv2_file_access_new_child, _idmefv2_file_access_destroy_child, NULL, NULL, (void *) idmefv2_file_access_copy, (void *) idmefv2_file_access_clone, (void *) idmefv2_file_access_compare, (void *) idmefv2_file_access_print, (void *) idmefv2_file_access_print_json, (void *) idmefv2_file_access_write, (void *) idmefv2_file_access_ref, (void *) idmefv2_file_access_destroy, 1 }, /* ID: 14 */
        { "inode", sizeof(idmefv2_inode_children_list) / sizeof(*idmefv2_inode_children_list), idmefv2_inode_children_list, _idmefv2_inode_get_child, _idmefv2_inode_new_child, _idmefv2_inode_destroy_child, NULL, NULL, (void *) idmefv2_inode_copy, (void *) idmefv2_inode_clone, (void *) idmefv2_inode_compare, (void *) idmefv2_inode_print, (void *) idmefv2_inode_print_json, (void *) idmefv2_inode_write, (void *) idmefv2_inode_ref, (void *) idmefv2_inode_destroy, 0 }, /* ID: 15 */
        { "checksum_algorithm", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_checksum_algorithm_to_numeric, (void *) idmefv2_checksum_algorithm_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 16  */
        { "checksum", sizeof(idmefv2_checksum_children_list) / sizeof(*idmefv2_checksum_children_list), idmefv2_checksum_children_list, _idmefv2_checksum_get_child, _idmefv2_checksum_new_child, _idmefv2_checksum_destroy_child, NULL, NULL, (void *) idmefv2_checksum_copy, (void *) idmefv2_checksum_clone, (void *) idmefv2_checksum_compare, (void *) idmefv2_checksum_print, (void *) idmefv2_checksum_print_json, (void *) idmefv2_checksum_write, (void *) idmefv2_checksum_ref, (void *) idmefv2_checksum_destroy, 1 }, /* ID: 17 */
        { "stream_offsetunit", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_stream_offsetunit_to_numeric, (void *) idmefv2_stream_offsetunit_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 18  */
        { "stream", sizeof(idmefv2_stream_children_list) / sizeof(*idmefv2_stream_children_list), idmefv2_stream_children_list, _idmefv2_stream_get_child, _idmefv2_stream_new_child, _idmefv2_stream_destroy_child, NULL, NULL, (void *) idmefv2_stream_copy, (void *) idmefv2_stream_clone, (void *) idmefv2_stream_compare, (void *) idmefv2_stream_print, (void *) idmefv2_stream_print_json, (void *) idmefv2_stream_write, (void *) idmefv2_stream_ref, (void *) idmefv2_stream_destroy, 0 }, /* ID: 19 */
        { "file_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_file_category_to_numeric, (void *) idmefv2_file_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 20  */
        { "file", sizeof(idmefv2_file_children_list) / sizeof(*idmefv2_file_children_list), idmefv2_file_children_list, _idmefv2_file_get_child, _idmefv2_file_new_child, _idmefv2_file_destroy_child, NULL, NULL, (void *) idmefv2_file_copy, (void *) idmefv2_file_clone, (void *) idmefv2_file_compare, (void *) idmefv2_file_print, (void *) idmefv2_file_print_json, (void *) idmefv2_file_write, (void *) idmefv2_file_ref, (void *) idmefv2_file_destroy, 0 }, /* ID: 21 */
        { "linkage_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_linkage_category_to_numeric, (void *) idmefv2_linkage_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 22  */
        { "linkage", sizeof(idmefv2_linkage_children_list) / sizeof(*idmefv2_linkage_children_list), idmefv2_linkage_children_list, _idmefv2_linkage_get_child, _idmefv2_linkage_new_child, _idmefv2_linkage_destroy_child, NULL, NULL, (void *) idmefv2_linkage_copy, (void *) idmefv2_linkage_clone, (void *) idmefv2_linkage_compare, (void *) idmefv2_linkage_print, (void *) idmefv2_linkage_print_json, (void *) idmefv2_linkage_write, (void *) idmefv2_linkage_ref, (void *) idmefv2_linkage_destroy, 1 }, /* ID: 23 */
        { "container", sizeof(idmefv2_container_children_list) / sizeof(*idmefv2_container_children_list), idmefv2_container_children_list, _idmefv2_container_get_child, _idmefv2_container_new_child, _idmefv2_container_destroy_child, NULL, NULL, (void *) idmefv2_container_copy, (void *) idmefv2_container_clone, (void *) idmefv2_container_compare, (void *) idmefv2_container_print, (void *) idmefv2_container_print_json, (void *) idmefv2_container_write, (void *) idmefv2_container_ref, (void *) idmefv2_container_destroy, 0 }, /* ID: 24 */
        { "process", sizeof(idmefv2_process_children_list) / sizeof(*idmefv2_process_children_list), idmefv2_process_children_list, _idmefv2_process_get_child, _idmefv2_process_new_child, _idmefv2_process_destroy_child, NULL, NULL, (void *) idmefv2_process_copy, (void *) idmefv2_process_clone, (void *) idmefv2_process_compare, (void *) idmefv2_process_print, (void *) idmefv2_process_print_json, (void *) idmefv2_process_write, (void *) idmefv2_process_ref, (void *) idmefv2_process_destroy, 0 }, /* ID: 25 */
        { "service", sizeof(idmefv2_service_children_list) / sizeof(*idmefv2_service_children_list), idmefv2_service_children_list, _idmefv2_service_get_child, _idmefv2_service_new_child, _idmefv2_service_destroy_child, NULL, NULL, (void *) idmefv2_service_copy, (void *) idmefv2_service_clone, (void *) idmefv2_service_compare, (void *) idmefv2_service_print, (void *) idmefv2_service_print_json, (void *) idmefv2_service_write, (void *) idmefv2_service_ref, (void *) idmefv2_service_destroy, 0 }, /* ID: 26 */
        { "node", sizeof(idmefv2_node_children_list) / sizeof(*idmefv2_node_children_list), idmefv2_node_children_list, _idmefv2_node_get_child, _idmefv2_node_new_child, _idmefv2_node_destroy_child, NULL, NULL, (void *) idmefv2_node_copy, (void *) idmefv2_node_clone, (void *) idmefv2_node_compare, (void *) idmefv2_node_print, (void *) idmefv2_node_print_json, (void *) idmefv2_node_write, (void *) idmefv2_node_ref, (void *) idmefv2_node_destroy, 0 }, /* ID: 27 */
        { "user_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_user_category_to_numeric, (void *) idmefv2_user_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 28  */
        { "user", sizeof(idmefv2_user_children_list) / sizeof(*idmefv2_user_children_list), idmefv2_user_children_list, _idmefv2_user_get_child, _idmefv2_user_new_child, _idmefv2_user_destroy_child, NULL, NULL, (void *) idmefv2_user_copy, (void *) idmefv2_user_clone, (void *) idmefv2_user_compare, (void *) idmefv2_user_print, (void *) idmefv2_user_print_json, (void *) idmefv2_user_write, (void *) idmefv2_user_ref, (void *) idmefv2_user_destroy, 0 }, /* ID: 29 */
        { "impact_type_origin", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_impact_type_origin_to_numeric, (void *) idmefv2_impact_type_origin_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 30  */
        { "impact_type", sizeof(idmefv2_impact_type_children_list) / sizeof(*idmefv2_impact_type_children_list), idmefv2_impact_type_children_list, _idmefv2_impact_type_get_child, _idmefv2_impact_type_new_child, _idmefv2_impact_type_destroy_child, NULL, NULL, (void *) idmefv2_impact_type_copy, (void *) idmefv2_impact_type_clone, (void *) idmefv2_impact_type_compare, (void *) idmefv2_impact_type_print, (void *) idmefv2_impact_type_print_json, (void *) idmefv2_impact_type_write, (void *) idmefv2_impact_type_ref, (void *) idmefv2_impact_type_destroy, 1 }, /* ID: 31 */
        { "source_spoofed", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_source_spoofed_to_numeric, (void *) idmefv2_source_spoofed_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 32  */
        { "source", sizeof(idmefv2_source_children_list) / sizeof(*idmefv2_source_children_list), idmefv2_source_children_list, _idmefv2_source_get_child, _idmefv2_source_new_child, _idmefv2_source_destroy_child, NULL, NULL, (void *) idmefv2_source_copy, (void *) idmefv2_source_clone, (void *) idmefv2_source_compare, (void *) idmefv2_source_print, (void *) idmefv2_source_print_json, (void *) idmefv2_source_write, (void *) idmefv2_source_ref, (void *) idmefv2_source_destroy, 1 }, /* ID: 33 */
        { "target_decoy", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_target_decoy_to_numeric, (void *) idmefv2_target_decoy_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 34  */
        { "target", sizeof(idmefv2_target_children_list) / sizeof(*idmefv2_target_children_list), idmefv2_target_children_list, _idmefv2_target_get_child, _idmefv2_target_new_child, _idmefv2_target_destroy_child, NULL, NULL, (void *) idmefv2_target_copy, (void *) idmefv2_target_clone, (void *) idmefv2_target_compare, (void *) idmefv2_target_print, (void *) idmefv2_target_print_json, (void *) idmefv2_target_write, (void *) idmefv2_target_ref, (void *) idmefv2_target_destroy, 1 }, /* ID: 35 */
        { "original_data", sizeof(idmefv2_original_data_children_list) / sizeof(*idmefv2_original_data_children_list), idmefv2_original_data_children_list, _idmefv2_original_data_get_child, _idmefv2_original_data_new_child, _idmefv2_original_data_destroy_child, NULL, NULL, (void *) idmefv2_original_data_copy, (void *) idmefv2_original_data_clone, (void *) idmefv2_original_data_compare, (void *) idmefv2_original_data_print, (void *) idmefv2_original_data_print_json, (void *) idmefv2_original_data_write, (void *) idmefv2_original_data_ref, (void *) idmefv2_original_data_destroy, 1 }, /* ID: 36 */
        { "observable_origin", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_observable_origin_to_numeric, (void *) idmefv2_observable_origin_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 37  */
        { "observable", sizeof(idmefv2_observable_children_list) / sizeof(*idmefv2_observable_children_list), idmefv2_observable_children_list, _idmefv2_observable_get_child, _idmefv2_observable_new_child, _idmefv2_observable_destroy_child, NULL, NULL, (void *) idmefv2_observable_copy, (void *) idmefv2_observable_clone, (void *) idmefv2_observable_compare, (void *) idmefv2_observable_print, (void *) idmefv2_observable_print_json, (void *) idmefv2_observable_write, (void *) idmefv2_observable_ref, (void *) idmefv2_observable_destroy, 1 }, /* ID: 38 */
        { "taken_action_category", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_taken_action_category_to_numeric, (void *) idmefv2_taken_action_category_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 39  */
        { "taken_action", sizeof(idmefv2_taken_action_children_list) / sizeof(*idmefv2_taken_action_children_list), idmefv2_taken_action_children_list, _idmefv2_taken_action_get_child, _idmefv2_taken_action_new_child, _idmefv2_taken_action_destroy_child, NULL, NULL, (void *) idmefv2_taken_action_copy, (void *) idmefv2_taken_action_clone, (void *) idmefv2_taken_action_compare, (void *) idmefv2_taken_action_print, (void *) idmefv2_taken_action_print_json, (void *) idmefv2_taken_action_write, (void *) idmefv2_taken_action_ref, (void *) idmefv2_taken_action_destroy, 1 }, /* ID: 40 */
        { "reference_origin", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_reference_origin_to_numeric, (void *) idmefv2_reference_origin_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 41  */
        { "reference", sizeof(idmefv2_reference_children_list) / sizeof(*idmefv2_reference_children_list), idmefv2_reference_children_list, _idmefv2_reference_get_child, _idmefv2_reference_new_child, _idmefv2_reference_destroy_child, NULL, NULL, (void *) idmefv2_reference_copy, (void *) idmefv2_reference_clone, (void *) idmefv2_reference_compare, (void *) idmefv2_reference_print, (void *) idmefv2_reference_print_json, (void *) idmefv2_reference_write, (void *) idmefv2_reference_ref, (void *) idmefv2_reference_destroy, 1 }, /* ID: 42 */
        { "analyzer", sizeof(idmefv2_analyzer_children_list) / sizeof(*idmefv2_analyzer_children_list), idmefv2_analyzer_children_list, _idmefv2_analyzer_get_child, _idmefv2_analyzer_new_child, _idmefv2_analyzer_destroy_child, NULL, NULL, (void *) idmefv2_analyzer_copy, (void *) idmefv2_analyzer_clone, (void *) idmefv2_analyzer_compare, (void *) idmefv2_analyzer_print, (void *) idmefv2_analyzer_print_json, (void *) idmefv2_analyzer_write, (void *) idmefv2_analyzer_ref, (void *) idmefv2_analyzer_destroy, 1 }, /* ID: 43 */
        { "additional_data_type", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_additional_data_type_to_numeric, (void *) idmefv2_additional_data_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 44  */
        { "additional_data", sizeof(idmefv2_additional_data_children_list) / sizeof(*idmefv2_additional_data_children_list), idmefv2_additional_data_children_list, _idmefv2_additional_data_get_child, _idmefv2_additional_data_new_child, _idmefv2_additional_data_destroy_child, NULL, NULL, (void *) idmefv2_additional_data_copy, (void *) idmefv2_additional_data_clone, (void *) idmefv2_additional_data_compare, (void *) idmefv2_additional_data_print, (void *) idmefv2_additional_data_print_json, (void *) idmefv2_additional_data_write, (void *) idmefv2_additional_data_ref, (void *) idmefv2_additional_data_destroy, 1 }, /* ID: 45 */
        { "correlation_alert", sizeof(idmefv2_correlation_alert_children_list) / sizeof(*idmefv2_correlation_alert_children_list), idmefv2_correlation_alert_children_list, _idmefv2_correlation_alert_get_child, _idmefv2_correlation_alert_new_child, _idmefv2_correlation_alert_destroy_child, NULL, NULL, (void *) idmefv2_correlation_alert_copy, (void *) idmefv2_correlation_alert_clone, (void *) idmefv2_correlation_alert_compare, (void *) idmefv2_correlation_alert_print, (void *) idmefv2_correlation_alert_print_json, (void *) idmefv2_correlation_alert_write, (void *) idmefv2_correlation_alert_ref, (void *) idmefv2_correlation_alert_destroy, 0 }, /* ID: 46 */
        { "analysis_data", sizeof(idmefv2_analysis_data_children_list) / sizeof(*idmefv2_analysis_data_children_list), idmefv2_analysis_data_children_list, _idmefv2_analysis_data_get_child, _idmefv2_analysis_data_new_child, _idmefv2_analysis_data_destroy_child, NULL, NULL, (void *) idmefv2_analysis_data_copy, (void *) idmefv2_analysis_data_clone, (void *) idmefv2_analysis_data_compare, (void *) idmefv2_analysis_data_print, (void *) idmefv2_analysis_data_print_json, (void *) idmefv2_analysis_data_write, (void *) idmefv2_analysis_data_ref, (void *) idmefv2_analysis_data_destroy, 0 }, /* ID: 47 */
        { "confidence_rating", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_confidence_rating_to_numeric, (void *) idmefv2_confidence_rating_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 48  */
        { "confidence", sizeof(idmefv2_confidence_children_list) / sizeof(*idmefv2_confidence_children_list), idmefv2_confidence_children_list, _idmefv2_confidence_get_child, _idmefv2_confidence_new_child, _idmefv2_confidence_destroy_child, NULL, NULL, (void *) idmefv2_confidence_copy, (void *) idmefv2_confidence_clone, (void *) idmefv2_confidence_compare, (void *) idmefv2_confidence_print, (void *) idmefv2_confidence_print_json, (void *) idmefv2_confidence_write, (void *) idmefv2_confidence_ref, (void *) idmefv2_confidence_destroy, 0 }, /* ID: 49 */
        { "impact_completion", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_impact_completion_to_numeric, (void *) idmefv2_impact_completion_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 50  */
        { "impact_severity", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_impact_severity_to_numeric, (void *) idmefv2_impact_severity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 51  */
        { "impact_availability", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_impact_availability_to_numeric, (void *) idmefv2_impact_availability_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 52  */
        { "impact_integrity", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_impact_integrity_to_numeric, (void *) idmefv2_impact_integrity_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 53  */
        { "impact_confidentiality", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_impact_confidentiality_to_numeric, (void *) idmefv2_impact_confidentiality_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 54  */
        { "impact", sizeof(idmefv2_impact_children_list) / sizeof(*idmefv2_impact_children_list), idmefv2_impact_children_list, _idmefv2_impact_get_child, _idmefv2_impact_new_child, _idmefv2_impact_destroy_child, NULL, NULL, (void *) idmefv2_impact_copy, (void *) idmefv2_impact_clone, (void *) idmefv2_impact_compare, (void *) idmefv2_impact_print, (void *) idmefv2_impact_print_json, (void *) idmefv2_impact_write, (void *) idmefv2_impact_ref, (void *) idmefv2_impact_destroy, 0 }, /* ID: 55 */
        { "recommanded_action", sizeof(idmefv2_recommanded_action_children_list) / sizeof(*idmefv2_recommanded_action_children_list), idmefv2_recommanded_action_children_list, _idmefv2_recommanded_action_get_child, _idmefv2_recommanded_action_new_child, _idmefv2_recommanded_action_destroy_child, NULL, NULL, (void *) idmefv2_recommanded_action_copy, (void *) idmefv2_recommanded_action_clone, (void *) idmefv2_recommanded_action_compare, (void *) idmefv2_recommanded_action_print, (void *) idmefv2_recommanded_action_print_json, (void *) idmefv2_recommanded_action_write, (void *) idmefv2_recommanded_action_ref, (void *) idmefv2_recommanded_action_destroy, 1 }, /* ID: 56 */
        { "assessment", sizeof(idmefv2_assessment_children_list) / sizeof(*idmefv2_assessment_children_list), idmefv2_assessment_children_list, _idmefv2_assessment_get_child, _idmefv2_assessment_new_child, _idmefv2_assessment_destroy_child, NULL, NULL, (void *) idmefv2_assessment_copy, (void *) idmefv2_assessment_clone, (void *) idmefv2_assessment_compare, (void *) idmefv2_assessment_print, (void *) idmefv2_assessment_print_json, (void *) idmefv2_assessment_write, (void *) idmefv2_assessment_ref, (void *) idmefv2_assessment_destroy, 0 }, /* ID: 57 */
        { "classification", sizeof(idmefv2_classification_children_list) / sizeof(*idmefv2_classification_children_list), idmefv2_classification_children_list, _idmefv2_classification_get_child, _idmefv2_classification_new_child, _idmefv2_classification_destroy_child, NULL, NULL, (void *) idmefv2_classification_copy, (void *) idmefv2_classification_clone, (void *) idmefv2_classification_compare, (void *) idmefv2_classification_print, (void *) idmefv2_classification_print_json, (void *) idmefv2_classification_write, (void *) idmefv2_classification_ref, (void *) idmefv2_classification_destroy, 0 }, /* ID: 58 */
        { "heartbeat", sizeof(idmefv2_heartbeat_children_list) / sizeof(*idmefv2_heartbeat_children_list), idmefv2_heartbeat_children_list, _idmefv2_heartbeat_get_child, _idmefv2_heartbeat_new_child, _idmefv2_heartbeat_destroy_child, NULL, NULL, (void *) idmefv2_heartbeat_copy, (void *) idmefv2_heartbeat_clone, (void *) idmefv2_heartbeat_compare, (void *) idmefv2_heartbeat_print, (void *) idmefv2_heartbeat_print_json, (void *) idmefv2_heartbeat_write, (void *) idmefv2_heartbeat_ref, (void *) idmefv2_heartbeat_destroy, 0 }, /* ID: 59 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 60 */
        { "(unassigned)", 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }, /* ID: 61 */
        { "alert_type", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_alert_type_to_numeric, (void *) idmefv2_alert_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 62  */
        { "alert", sizeof(idmefv2_alert_children_list) / sizeof(*idmefv2_alert_children_list), idmefv2_alert_children_list, _idmefv2_alert_get_child, _idmefv2_alert_new_child, _idmefv2_alert_destroy_child, NULL, NULL, (void *) idmefv2_alert_copy, (void *) idmefv2_alert_clone, (void *) idmefv2_alert_compare, (void *) idmefv2_alert_print, (void *) idmefv2_alert_print_json, (void *) idmefv2_alert_write, (void *) idmefv2_alert_ref, (void *) idmefv2_alert_destroy, 0 }, /* ID: 63 */
        { "message_type", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_message_type_to_numeric, (void *) idmefv2_message_type_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 64  */
        { "message", sizeof(idmefv2_message_children_list) / sizeof(*idmefv2_message_children_list), idmefv2_message_children_list, _idmefv2_message_get_child, _idmefv2_message_new_child, _idmefv2_message_destroy_child, NULL, NULL, (void *) idmefv2_message_copy, (void *) idmefv2_message_clone, (void *) idmefv2_message_compare, (void *) idmefv2_message_print, (void *) idmefv2_message_print_json, (void *) idmefv2_message_write, (void *) idmefv2_message_ref, (void *) idmefv2_message_destroy, 0 }, /* ID: 65 */
        { "analyzer_class", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_analyzer_class_to_numeric, (void *) idmefv2_analyzer_class_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 66  */
        { "analyzer_analyzeraction", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_analyzer_analyzeraction_to_numeric, (void *) idmefv2_analyzer_analyzeraction_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 67  */
        { "recommanded_action_action", 0, NULL, NULL, NULL, NULL, (void *) idmefv2_recommanded_action_action_to_numeric, (void *) idmefv2_recommanded_action_action_to_string, NULL, NULL, NULL, NULL, NULL, 0 },/* ID: 68  */
        { NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }
};
